//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Code/Scripts/Input/PlayerInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputActionsClass : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputActionsClass()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputActions"",
    ""maps"": [
        {
            ""name"": ""OnFoot"",
            ""id"": ""1f2cfbc4-0714-4585-a1cf-0b3e4346071c"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""ec9a118f-f471-4763-958c-3b65c1bcb9a7"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": ""NormalizeVector2"",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Camera"",
                    ""type"": ""Value"",
                    ""id"": ""b52e79b6-e01b-44ad-af3c-15f5f24d52ae"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Attack"",
                    ""type"": ""Button"",
                    ""id"": ""a067ce1d-96c1-4d1d-a040-d18e7fa088a0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""aad01cbe-c7dd-4f2b-881e-4743d81dfb7a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""035e6cb8-fc40-4414-81b3-1d55a209c1c3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Crouch"",
                    ""type"": ""Button"",
                    ""id"": ""de0325c9-cacc-466f-8975-3c3c6b6906ab"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Sprint"",
                    ""type"": ""Button"",
                    ""id"": ""392a89eb-bebe-4c93-97cd-b8f388974d5b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Inventory"",
                    ""type"": ""Button"",
                    ""id"": ""0001202c-b4ef-481a-9a73-8bb695561839"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""0c94e780-9b57-457e-ba32-c6b42630a182"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SlotChange"",
                    ""type"": ""Value"",
                    ""id"": ""7e725306-ea20-4452-b5ee-bc5219d14a34"",
                    ""expectedControlType"": ""Analog"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""SlotSet_1"",
                    ""type"": ""Button"",
                    ""id"": ""6d215c40-d20a-408c-8890-51e353f2edde"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SlotSet_2"",
                    ""type"": ""Button"",
                    ""id"": ""bd7a9c6a-11f2-4110-b0e7-c93148e941c2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SlotSet_3"",
                    ""type"": ""Button"",
                    ""id"": ""0f5d71d0-6e2a-4990-bba5-4d99fc7064ed"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SlotSet_4"",
                    ""type"": ""Button"",
                    ""id"": ""d450f161-95b4-4295-bef4-419423d6d6fc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SlotSet_5"",
                    ""type"": ""Button"",
                    ""id"": ""a317bbaa-39ba-4680-9ea3-5f759264ec8d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SlotSet_6"",
                    ""type"": ""Button"",
                    ""id"": ""097e1316-a068-4c49-8297-2dbdbed29d34"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SlotSet_7"",
                    ""type"": ""Button"",
                    ""id"": ""15ca1fc8-c080-4bf8-98e3-548ff5508ddb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SlotSet_8"",
                    ""type"": ""Button"",
                    ""id"": ""0380b6fa-0726-4764-9758-9a2c09074767"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SlotSet_9"",
                    ""type"": ""Button"",
                    ""id"": ""d5e31083-f8d6-48ca-9bb7-37fc8ff300b0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MousePos"",
                    ""type"": ""Value"",
                    ""id"": ""7df6643f-d2fe-4478-a595-d5f0a48214cb"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""78b86440-2d34-41a9-8628-8e90e9e114cd"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""WASD"",
                    ""id"": ""f1143a7f-d0d3-433c-a461-f02e17164159"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""da9f66fa-a0a8-4a90-b2b5-690ead80f2c4"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""b71734f2-ec2d-422e-b11c-0647415afbda"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""97a3c0ae-0867-432b-925c-12dffac567eb"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""b7086df6-1dfd-4365-a719-05f2821ff617"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""76a2bc50-3673-4939-848e-57aff22181e7"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": ""ScaleVector2(x=1.5,y=1.5)"",
                    ""groups"": """",
                    ""action"": ""Camera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b4e0c0db-e4d3-498b-9db4-a48a37a0046f"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Camera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""07023b98-8a99-4a2e-af31-493461c607ba"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4e092502-64a3-4e58-98b0-97bb59525dac"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""38cde0ab-2477-4272-8ae4-60d838a1996c"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dd393f89-e16a-4376-af12-0df142af7261"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""03ba6c0c-d77d-4bce-b8bd-ce1f6a2009da"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1d900d4c-4754-47e8-ab57-b01be6957f2b"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Crouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""92d4bf45-7e27-4a77-b43c-4c4b67b4a136"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Crouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b512e0b1-f05a-4fb1-aafc-ab801464fe8e"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Sprint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""61d3e21f-1e0a-4dad-87f7-6182f13ae427"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Sprint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b97206ed-47b7-4e59-b9c0-e4030edd6b90"",
                    ""path"": ""<Gamepad>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Inventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cd69a06b-d512-41d2-a2dd-5e6390a6e92f"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""37324074-3cf9-4a1b-a5bc-1858c9f28600"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6f76a3bd-e87d-48ba-af2e-45b2cccbff73"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""76dd3776-941d-4e91-89a5-6cab1649a54d"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Inventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4f69bad4-2a40-44ca-979c-d01ce20ed48a"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SlotSet_1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d6337487-ff9e-4a0d-8a2e-83eb28a50ec7"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SlotSet_1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a46f6718-5d2f-4fb7-9b78-5ec0b84b8ae8"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SlotSet_2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""840aa173-bce1-42ac-914d-b3702c94214b"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SlotSet_2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""528c3296-042f-4a1e-ac16-d9611bd55e8f"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SlotSet_3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ac05589b-930f-4d25-a9ac-55e6e22adb44"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SlotSet_3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b1169f74-4fa8-437a-b714-d7f40cbefd87"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SlotSet_4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""89f0253c-d714-4b2e-a26c-725eb8c53b79"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SlotSet_4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b7566470-0946-4171-93d5-bc355a4daa63"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SlotSet_5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c6d7ed71-b88c-41b1-ad7c-0d7aaaeaeb2a"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SlotSet_5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0bc6d85d-a067-4e02-9513-a305df0e3182"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SlotSet_6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d0c4c80f-eb03-4b18-a108-c123bda8e31f"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SlotSet_6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""414d9898-4623-4a24-875b-87f707bbe704"",
                    ""path"": ""<Keyboard>/7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SlotSet_7"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b44c1e15-6efd-4c06-b034-97365c856f20"",
                    ""path"": ""<Keyboard>/7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SlotSet_7"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""03cf2f76-5ef9-4f0e-a608-c43302b2f9d2"",
                    ""path"": ""<Keyboard>/8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SlotSet_8"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7944689b-4afe-4545-b2d2-3c460c5aa4b8"",
                    ""path"": ""<Keyboard>/8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SlotSet_8"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9b1c8320-351d-49a1-83f0-bb053a676e74"",
                    ""path"": ""<Keyboard>/9"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SlotSet_9"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5abe1e61-a8f0-4641-9314-f0100fe881f3"",
                    ""path"": ""<Keyboard>/9"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SlotSet_9"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""1D Axis Gamepad"",
                    ""id"": ""267c3cc9-0122-4075-a7dd-4eaf26d50a25"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SlotChange"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""d71816ab-9e95-4a32-a42e-2cead6c25080"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SlotChange"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""79e013dd-591f-4c0f-abbd-1e01ac22494c"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SlotChange"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""675a1fed-b5bb-49b4-8551-5ed3532e5970"",
                    ""path"": ""<Mouse>/scroll/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SlotChange"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d285d0d1-6539-4897-8d0f-da0e9b1c505b"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MousePos"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""01abde0c-cfaf-4a89-82b0-62a3a7a96325"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MousePos"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // OnFoot
        m_OnFoot = asset.FindActionMap("OnFoot", throwIfNotFound: true);
        m_OnFoot_Movement = m_OnFoot.FindAction("Movement", throwIfNotFound: true);
        m_OnFoot_Camera = m_OnFoot.FindAction("Camera", throwIfNotFound: true);
        m_OnFoot_Attack = m_OnFoot.FindAction("Attack", throwIfNotFound: true);
        m_OnFoot_Interact = m_OnFoot.FindAction("Interact", throwIfNotFound: true);
        m_OnFoot_Jump = m_OnFoot.FindAction("Jump", throwIfNotFound: true);
        m_OnFoot_Crouch = m_OnFoot.FindAction("Crouch", throwIfNotFound: true);
        m_OnFoot_Sprint = m_OnFoot.FindAction("Sprint", throwIfNotFound: true);
        m_OnFoot_Inventory = m_OnFoot.FindAction("Inventory", throwIfNotFound: true);
        m_OnFoot_Pause = m_OnFoot.FindAction("Pause", throwIfNotFound: true);
        m_OnFoot_SlotChange = m_OnFoot.FindAction("SlotChange", throwIfNotFound: true);
        m_OnFoot_SlotSet_1 = m_OnFoot.FindAction("SlotSet_1", throwIfNotFound: true);
        m_OnFoot_SlotSet_2 = m_OnFoot.FindAction("SlotSet_2", throwIfNotFound: true);
        m_OnFoot_SlotSet_3 = m_OnFoot.FindAction("SlotSet_3", throwIfNotFound: true);
        m_OnFoot_SlotSet_4 = m_OnFoot.FindAction("SlotSet_4", throwIfNotFound: true);
        m_OnFoot_SlotSet_5 = m_OnFoot.FindAction("SlotSet_5", throwIfNotFound: true);
        m_OnFoot_SlotSet_6 = m_OnFoot.FindAction("SlotSet_6", throwIfNotFound: true);
        m_OnFoot_SlotSet_7 = m_OnFoot.FindAction("SlotSet_7", throwIfNotFound: true);
        m_OnFoot_SlotSet_8 = m_OnFoot.FindAction("SlotSet_8", throwIfNotFound: true);
        m_OnFoot_SlotSet_9 = m_OnFoot.FindAction("SlotSet_9", throwIfNotFound: true);
        m_OnFoot_MousePos = m_OnFoot.FindAction("MousePos", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // OnFoot
    private readonly InputActionMap m_OnFoot;
    private IOnFootActions m_OnFootActionsCallbackInterface;
    private readonly InputAction m_OnFoot_Movement;
    private readonly InputAction m_OnFoot_Camera;
    private readonly InputAction m_OnFoot_Attack;
    private readonly InputAction m_OnFoot_Interact;
    private readonly InputAction m_OnFoot_Jump;
    private readonly InputAction m_OnFoot_Crouch;
    private readonly InputAction m_OnFoot_Sprint;
    private readonly InputAction m_OnFoot_Inventory;
    private readonly InputAction m_OnFoot_Pause;
    private readonly InputAction m_OnFoot_SlotChange;
    private readonly InputAction m_OnFoot_SlotSet_1;
    private readonly InputAction m_OnFoot_SlotSet_2;
    private readonly InputAction m_OnFoot_SlotSet_3;
    private readonly InputAction m_OnFoot_SlotSet_4;
    private readonly InputAction m_OnFoot_SlotSet_5;
    private readonly InputAction m_OnFoot_SlotSet_6;
    private readonly InputAction m_OnFoot_SlotSet_7;
    private readonly InputAction m_OnFoot_SlotSet_8;
    private readonly InputAction m_OnFoot_SlotSet_9;
    private readonly InputAction m_OnFoot_MousePos;
    public struct OnFootActions
    {
        private @PlayerInputActionsClass m_Wrapper;
        public OnFootActions(@PlayerInputActionsClass wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_OnFoot_Movement;
        public InputAction @Camera => m_Wrapper.m_OnFoot_Camera;
        public InputAction @Attack => m_Wrapper.m_OnFoot_Attack;
        public InputAction @Interact => m_Wrapper.m_OnFoot_Interact;
        public InputAction @Jump => m_Wrapper.m_OnFoot_Jump;
        public InputAction @Crouch => m_Wrapper.m_OnFoot_Crouch;
        public InputAction @Sprint => m_Wrapper.m_OnFoot_Sprint;
        public InputAction @Inventory => m_Wrapper.m_OnFoot_Inventory;
        public InputAction @Pause => m_Wrapper.m_OnFoot_Pause;
        public InputAction @SlotChange => m_Wrapper.m_OnFoot_SlotChange;
        public InputAction @SlotSet_1 => m_Wrapper.m_OnFoot_SlotSet_1;
        public InputAction @SlotSet_2 => m_Wrapper.m_OnFoot_SlotSet_2;
        public InputAction @SlotSet_3 => m_Wrapper.m_OnFoot_SlotSet_3;
        public InputAction @SlotSet_4 => m_Wrapper.m_OnFoot_SlotSet_4;
        public InputAction @SlotSet_5 => m_Wrapper.m_OnFoot_SlotSet_5;
        public InputAction @SlotSet_6 => m_Wrapper.m_OnFoot_SlotSet_6;
        public InputAction @SlotSet_7 => m_Wrapper.m_OnFoot_SlotSet_7;
        public InputAction @SlotSet_8 => m_Wrapper.m_OnFoot_SlotSet_8;
        public InputAction @SlotSet_9 => m_Wrapper.m_OnFoot_SlotSet_9;
        public InputAction @MousePos => m_Wrapper.m_OnFoot_MousePos;
        public InputActionMap Get() { return m_Wrapper.m_OnFoot; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(OnFootActions set) { return set.Get(); }
        public void SetCallbacks(IOnFootActions instance)
        {
            if (m_Wrapper.m_OnFootActionsCallbackInterface != null)
            {
                @Movement.started -= m_Wrapper.m_OnFootActionsCallbackInterface.OnMovement;
                @Movement.performed -= m_Wrapper.m_OnFootActionsCallbackInterface.OnMovement;
                @Movement.canceled -= m_Wrapper.m_OnFootActionsCallbackInterface.OnMovement;
                @Camera.started -= m_Wrapper.m_OnFootActionsCallbackInterface.OnCamera;
                @Camera.performed -= m_Wrapper.m_OnFootActionsCallbackInterface.OnCamera;
                @Camera.canceled -= m_Wrapper.m_OnFootActionsCallbackInterface.OnCamera;
                @Attack.started -= m_Wrapper.m_OnFootActionsCallbackInterface.OnAttack;
                @Attack.performed -= m_Wrapper.m_OnFootActionsCallbackInterface.OnAttack;
                @Attack.canceled -= m_Wrapper.m_OnFootActionsCallbackInterface.OnAttack;
                @Interact.started -= m_Wrapper.m_OnFootActionsCallbackInterface.OnInteract;
                @Interact.performed -= m_Wrapper.m_OnFootActionsCallbackInterface.OnInteract;
                @Interact.canceled -= m_Wrapper.m_OnFootActionsCallbackInterface.OnInteract;
                @Jump.started -= m_Wrapper.m_OnFootActionsCallbackInterface.OnJump;
                @Jump.performed -= m_Wrapper.m_OnFootActionsCallbackInterface.OnJump;
                @Jump.canceled -= m_Wrapper.m_OnFootActionsCallbackInterface.OnJump;
                @Crouch.started -= m_Wrapper.m_OnFootActionsCallbackInterface.OnCrouch;
                @Crouch.performed -= m_Wrapper.m_OnFootActionsCallbackInterface.OnCrouch;
                @Crouch.canceled -= m_Wrapper.m_OnFootActionsCallbackInterface.OnCrouch;
                @Sprint.started -= m_Wrapper.m_OnFootActionsCallbackInterface.OnSprint;
                @Sprint.performed -= m_Wrapper.m_OnFootActionsCallbackInterface.OnSprint;
                @Sprint.canceled -= m_Wrapper.m_OnFootActionsCallbackInterface.OnSprint;
                @Inventory.started -= m_Wrapper.m_OnFootActionsCallbackInterface.OnInventory;
                @Inventory.performed -= m_Wrapper.m_OnFootActionsCallbackInterface.OnInventory;
                @Inventory.canceled -= m_Wrapper.m_OnFootActionsCallbackInterface.OnInventory;
                @Pause.started -= m_Wrapper.m_OnFootActionsCallbackInterface.OnPause;
                @Pause.performed -= m_Wrapper.m_OnFootActionsCallbackInterface.OnPause;
                @Pause.canceled -= m_Wrapper.m_OnFootActionsCallbackInterface.OnPause;
                @SlotChange.started -= m_Wrapper.m_OnFootActionsCallbackInterface.OnSlotChange;
                @SlotChange.performed -= m_Wrapper.m_OnFootActionsCallbackInterface.OnSlotChange;
                @SlotChange.canceled -= m_Wrapper.m_OnFootActionsCallbackInterface.OnSlotChange;
                @SlotSet_1.started -= m_Wrapper.m_OnFootActionsCallbackInterface.OnSlotSet_1;
                @SlotSet_1.performed -= m_Wrapper.m_OnFootActionsCallbackInterface.OnSlotSet_1;
                @SlotSet_1.canceled -= m_Wrapper.m_OnFootActionsCallbackInterface.OnSlotSet_1;
                @SlotSet_2.started -= m_Wrapper.m_OnFootActionsCallbackInterface.OnSlotSet_2;
                @SlotSet_2.performed -= m_Wrapper.m_OnFootActionsCallbackInterface.OnSlotSet_2;
                @SlotSet_2.canceled -= m_Wrapper.m_OnFootActionsCallbackInterface.OnSlotSet_2;
                @SlotSet_3.started -= m_Wrapper.m_OnFootActionsCallbackInterface.OnSlotSet_3;
                @SlotSet_3.performed -= m_Wrapper.m_OnFootActionsCallbackInterface.OnSlotSet_3;
                @SlotSet_3.canceled -= m_Wrapper.m_OnFootActionsCallbackInterface.OnSlotSet_3;
                @SlotSet_4.started -= m_Wrapper.m_OnFootActionsCallbackInterface.OnSlotSet_4;
                @SlotSet_4.performed -= m_Wrapper.m_OnFootActionsCallbackInterface.OnSlotSet_4;
                @SlotSet_4.canceled -= m_Wrapper.m_OnFootActionsCallbackInterface.OnSlotSet_4;
                @SlotSet_5.started -= m_Wrapper.m_OnFootActionsCallbackInterface.OnSlotSet_5;
                @SlotSet_5.performed -= m_Wrapper.m_OnFootActionsCallbackInterface.OnSlotSet_5;
                @SlotSet_5.canceled -= m_Wrapper.m_OnFootActionsCallbackInterface.OnSlotSet_5;
                @SlotSet_6.started -= m_Wrapper.m_OnFootActionsCallbackInterface.OnSlotSet_6;
                @SlotSet_6.performed -= m_Wrapper.m_OnFootActionsCallbackInterface.OnSlotSet_6;
                @SlotSet_6.canceled -= m_Wrapper.m_OnFootActionsCallbackInterface.OnSlotSet_6;
                @SlotSet_7.started -= m_Wrapper.m_OnFootActionsCallbackInterface.OnSlotSet_7;
                @SlotSet_7.performed -= m_Wrapper.m_OnFootActionsCallbackInterface.OnSlotSet_7;
                @SlotSet_7.canceled -= m_Wrapper.m_OnFootActionsCallbackInterface.OnSlotSet_7;
                @SlotSet_8.started -= m_Wrapper.m_OnFootActionsCallbackInterface.OnSlotSet_8;
                @SlotSet_8.performed -= m_Wrapper.m_OnFootActionsCallbackInterface.OnSlotSet_8;
                @SlotSet_8.canceled -= m_Wrapper.m_OnFootActionsCallbackInterface.OnSlotSet_8;
                @SlotSet_9.started -= m_Wrapper.m_OnFootActionsCallbackInterface.OnSlotSet_9;
                @SlotSet_9.performed -= m_Wrapper.m_OnFootActionsCallbackInterface.OnSlotSet_9;
                @SlotSet_9.canceled -= m_Wrapper.m_OnFootActionsCallbackInterface.OnSlotSet_9;
                @MousePos.started -= m_Wrapper.m_OnFootActionsCallbackInterface.OnMousePos;
                @MousePos.performed -= m_Wrapper.m_OnFootActionsCallbackInterface.OnMousePos;
                @MousePos.canceled -= m_Wrapper.m_OnFootActionsCallbackInterface.OnMousePos;
            }
            m_Wrapper.m_OnFootActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Movement.started += instance.OnMovement;
                @Movement.performed += instance.OnMovement;
                @Movement.canceled += instance.OnMovement;
                @Camera.started += instance.OnCamera;
                @Camera.performed += instance.OnCamera;
                @Camera.canceled += instance.OnCamera;
                @Attack.started += instance.OnAttack;
                @Attack.performed += instance.OnAttack;
                @Attack.canceled += instance.OnAttack;
                @Interact.started += instance.OnInteract;
                @Interact.performed += instance.OnInteract;
                @Interact.canceled += instance.OnInteract;
                @Jump.started += instance.OnJump;
                @Jump.performed += instance.OnJump;
                @Jump.canceled += instance.OnJump;
                @Crouch.started += instance.OnCrouch;
                @Crouch.performed += instance.OnCrouch;
                @Crouch.canceled += instance.OnCrouch;
                @Sprint.started += instance.OnSprint;
                @Sprint.performed += instance.OnSprint;
                @Sprint.canceled += instance.OnSprint;
                @Inventory.started += instance.OnInventory;
                @Inventory.performed += instance.OnInventory;
                @Inventory.canceled += instance.OnInventory;
                @Pause.started += instance.OnPause;
                @Pause.performed += instance.OnPause;
                @Pause.canceled += instance.OnPause;
                @SlotChange.started += instance.OnSlotChange;
                @SlotChange.performed += instance.OnSlotChange;
                @SlotChange.canceled += instance.OnSlotChange;
                @SlotSet_1.started += instance.OnSlotSet_1;
                @SlotSet_1.performed += instance.OnSlotSet_1;
                @SlotSet_1.canceled += instance.OnSlotSet_1;
                @SlotSet_2.started += instance.OnSlotSet_2;
                @SlotSet_2.performed += instance.OnSlotSet_2;
                @SlotSet_2.canceled += instance.OnSlotSet_2;
                @SlotSet_3.started += instance.OnSlotSet_3;
                @SlotSet_3.performed += instance.OnSlotSet_3;
                @SlotSet_3.canceled += instance.OnSlotSet_3;
                @SlotSet_4.started += instance.OnSlotSet_4;
                @SlotSet_4.performed += instance.OnSlotSet_4;
                @SlotSet_4.canceled += instance.OnSlotSet_4;
                @SlotSet_5.started += instance.OnSlotSet_5;
                @SlotSet_5.performed += instance.OnSlotSet_5;
                @SlotSet_5.canceled += instance.OnSlotSet_5;
                @SlotSet_6.started += instance.OnSlotSet_6;
                @SlotSet_6.performed += instance.OnSlotSet_6;
                @SlotSet_6.canceled += instance.OnSlotSet_6;
                @SlotSet_7.started += instance.OnSlotSet_7;
                @SlotSet_7.performed += instance.OnSlotSet_7;
                @SlotSet_7.canceled += instance.OnSlotSet_7;
                @SlotSet_8.started += instance.OnSlotSet_8;
                @SlotSet_8.performed += instance.OnSlotSet_8;
                @SlotSet_8.canceled += instance.OnSlotSet_8;
                @SlotSet_9.started += instance.OnSlotSet_9;
                @SlotSet_9.performed += instance.OnSlotSet_9;
                @SlotSet_9.canceled += instance.OnSlotSet_9;
                @MousePos.started += instance.OnMousePos;
                @MousePos.performed += instance.OnMousePos;
                @MousePos.canceled += instance.OnMousePos;
            }
        }
    }
    public OnFootActions @OnFoot => new OnFootActions(this);
    public interface IOnFootActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnCamera(InputAction.CallbackContext context);
        void OnAttack(InputAction.CallbackContext context);
        void OnInteract(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnCrouch(InputAction.CallbackContext context);
        void OnSprint(InputAction.CallbackContext context);
        void OnInventory(InputAction.CallbackContext context);
        void OnPause(InputAction.CallbackContext context);
        void OnSlotChange(InputAction.CallbackContext context);
        void OnSlotSet_1(InputAction.CallbackContext context);
        void OnSlotSet_2(InputAction.CallbackContext context);
        void OnSlotSet_3(InputAction.CallbackContext context);
        void OnSlotSet_4(InputAction.CallbackContext context);
        void OnSlotSet_5(InputAction.CallbackContext context);
        void OnSlotSet_6(InputAction.CallbackContext context);
        void OnSlotSet_7(InputAction.CallbackContext context);
        void OnSlotSet_8(InputAction.CallbackContext context);
        void OnSlotSet_9(InputAction.CallbackContext context);
        void OnMousePos(InputAction.CallbackContext context);
    }
}
